TEST_VALUE:
  name: “dev——cookie"
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a37d9e15e8a5900d
  FEISHU_APP_SECRET: zJT5XloAjmi7Nqp6wvFOfcroClC0RbhN
  REDIRECT_URL: http://www.baidu.com
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
MONGODB_CONFIG:
  name: "test"                       # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb+srv://woxigwj1212:woxigwj1212@test.xhihqcj.mongodb.net"   # 数据库链接地址
  username: "woxigwj1212"            # 数据库链接用户名
  password: "woxigwj1212"            # 数据库链接密码
  database: "test"                   # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                   # 是否开启同步数据表功能
  useUnifiedTopology: true                 
ZJ_LAB:
  APP_ID: 687f9918-23fa-4188-a150-f826e99b57ab
  server-url-prefix: https://onekey-test.zhejianglab.com/maxkey/authz/cas/
  server-login-url: https://onekey-test.zhejianglab.com/maxkey/authz/cas/687f9918-23fa-4188-a150-f826e99b57ab
  client-host-url: http://10.5.2.4:8889/
  validation-type: CAS3